apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-provider-frontend
spec:
  destination:
    name: ''
    namespace: saas-provider
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes
    repoURL: 'https://github.com/sam-andaluri/saas-provider-dot-cloud'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true