version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 427398298435.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t saas-react-app:latest .
      - docker tag saas-react-app:latest 427398298435.dkr.ecr.us-east-2.amazonaws.com/saas-react-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 427398298435.dkr.ecr.us-east-2.amazonaws.com/saas-react-app:latest
