steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg REACT_APP_AUTH0_DOMAIN=$$REACT_APP_AUTH0_DOMAIN --build-arg REACT_APP_AUTH0_CLIENT_ID=$$REACT_APP_AUTH0_CLIENT_ID --build-arg REACT_APP_TENANT_API_CLIENT_ID=$$REACT_APP_TENANT_API_CLIENT_ID --build-arg REACT_APP_TENANT_API_CLIENT_SECRET=$$REACT_APP_TENANT_API_CLIENT_SECRET --build-arg REACT_APP_TENANT_API_AUDIENCE=$$REACT_APP_TENANT_API_AUDIENCE -t $REPO_NAME:$TAG_NAME .']
    secretEnv: ['REACT_APP_AUTH0_CLIENT_ID','REACT_APP_AUTH0_DOMAIN','REACT_APP_TENANT_API_AUDIENCE','REACT_APP_TENANT_API_CLIENT_ID','REACT_APP_TENANT_API_CLIENT_SECRET']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push $REPO_NAME:$TAG_NAME']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/USERNAME/1
      env: 'USERNAME'
    - versionName: projects/$PROJECT_NUMBER/secrets/PASSWORD/1
      env: 'PASSWORD'
    - versionName: projects/$PROJECT_NUMBER/secrets/REACT_APP_AUTH0_CLIENT_ID/1
      env: 'REACT_APP_AUTH0_CLIENT_ID'
    - versionName: projects/$PROJECT_NUMBER/secrets/REACT_APP_AUTH0_DOMAIN/1
      env: 'REACT_APP_AUTH0_DOMAIN'
    - versionName: projects/$PROJECT_NUMBER/secrets/REACT_APP_TENANT_API_AUDIENCE/1
      env: 'REACT_APP_TENANT_API_AUDIENCE'
    - versionName: projects/$PROJECT_NUMBER/secrets/REACT_APP_TENANT_API_CLIENT_ID/1
      env: 'REACT_APP_TENANT_API_CLIENT_ID'
    - versionName: projects/$PROJECT_NUMBER/secrets/REACT_APP_TENANT_API_CLIENT_SECRET/1
      env: 'REACT_APP_TENANT_API_CLIENT_SECRET'
