apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-provider-frontend-deployment
  namespace: saas-provider-frontend
spec:
  template:
    spec:
      containers:
      - image: 427398298435.dkr.ecr.us-east-2.amazonaws.com/saas-provider-dot-cloud:latest
        name: saas-provider-frontend
