apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: provider
  namespace: saas-provider
spec:
  encryptedData:
    REACT_APP_AUTH0_CLIENT_ID: AgDJ9d2uJ0wEauRrq8VcMDqJTH/hMtTx2+T7bAOdWYklZRt4DEtAW4S9wDARVTAdE9wE5xvFLT5YB6LZPEhE6sA1bYfIeQJoeUP+JrYuPbVC4hyWE8oMOXZiD7yyt4rnAHilvRFCKmT4yTeLqhkjidc8pcc6G5wQiAq03zHhZYTlBVgqlIue6JD1VofK3/dF6ScI91lS7kvUG4yvdsUhmVOJk/nJFdRAYv+LtFw6nmj4072ixkFjanpzSJ1z1+jrD/LYfVHQfyfF4ZufPVnJidw7WI9cHpJVqgHoZOIaQVPqQvccNxMW3WpNl9HvH7+RpcDoBdwRSgQsf+stzogzK6PPPoHqcMJtZAJaAyjye4ntzELqRMsxpAYXHgbYB+pWo64wRTNCAdy16ysONk9uwEfSDxlOaSqYCKSCvOmLgegNTnHJ/MJSa0UUYnnYjQVpvAI7iqn3UiAFvnpHHB6trGnVwu2Bi0Bec7uQnFh+Beyf4MS5N2VI2an+/1Ou/r3IfkgRdo2dN1Y8qeODAUfqyR5DzpUpprv0WbJq8nz2MYfDf+EDMPPYgqBUI0dPmCp88fCI2uAU1en2VjunD2uPVv/VUklfCpPTFMEtC924bcYvF0ydsteowMVZNAzAVr0/NwnsPpa/K8zdG8Rp5qSkhkEs87q/Pig05PtUOy9gkAKv/7DjUQulD1WldfWgcd1ut9ub3hnjFGSVXbKJ1c2psmCvUZ+Rqhn3AYNgGOWOjGPd9g==
    REACT_APP_AUTH0_DOMAIN: AgDHSaPH9hWWxPKqAe2ia3AxTf0RawpKXTKzSKU4BkQ/XsKFFMOU4/D0oggzXTVu+KqB3BZE3XhOPQ/T/vhnpQqqUozPmNt+Ub4gIcySo+mJOTntbdSBhczMI1GvkFuO124rgLg6QCzcjwiA3HLhNiHIV9/JR6Bbzk7bg/+ODsGrjSqPcGCFP0ZCGW7GPsLrDT58D4DKJZjN21uxgjj5cw2z5Pc0vPrySSqwJxaeSEdFpqP37UgDiF0MrHUMYNWceJJIhkKPFSWkfBoK1PS8lqXqAGjVHHsich4GxhX8lcD/NjSw0Qca2YWFwfRdD0065xWmwP3a0R/Joajp5ard6uGY5hFONXlgkteTPnIPL31i8VLKaqWwzS8AOGhp+rZ5eF1BSl9e2HXZlSUAyxicVQxhXXRyL5/jsRFH9FzvomSGqO5M3+fiJrEqrmEicIGZGBEX93+I2C7foUmvlTlex8lbgHp8A599Hg1cfXp/FRGid1VFMz/guJeXr8ErJ/B0UJJetABuw9gi0Agi4iea2YqFShDvL2vWnzC8c0OyGLjfVJ3iqjMKRvu+KPmXLY61MQHAibqr7rSDDaff9EuwSXsegJFQ69yrue79MaJ3MOnvpOYIQ2GLcVwjvGchrTQ3A12FyOcW5ElMf/4u7hUd2hf401I4JzvksM31LlsY82e4rOTjyotf3gfQ1ITGjmMfZeBVRTvwzWZjLa/sGvS+Dt8EOeHkL2SQ2EfIZA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: provider
      namespace: saas-provider
    type: Opaque

