apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: provider
  namespace: default
spec:
  encryptedData:
    REACT_APP_AUTH0_CLIENT_ID: AgCeCpi4DZXAexU4bwhhZjLRH8xn5Xs4IYUSEQXTJDMoBkp4Uy0P1QKIYKWRRjtlU36XWBYpb53aq4sbpDi1aj1sF24dk8TRBe/rwycrv1dQ8IwtA+0hFN57ZQQA0+Y/L9Tp+z9NRXNu+FWNhxrN3S4VJpPL/xhQzzaM6QPMBQEr42fW77zvw7/V7MylzhDxLZyUqMoC9QfM9cf7O/UfbJFnAdQqpaUlQx/g057joRVyMnjSVAsSPh+EuZU57enxM79qkMF8ndW2qO68wWTRuDBwd7qjTexFzNabBJjQfCpBSB+EnlzIuqmABnxUljc9sDbJPP3IfDQHsMx3IgHG2vldsfHp2C4lw2BfYcBVxqXzfc0KEJ/vm98ORJWx3ikbRm7Brq3TjkjFhjpKwPSK4T77DvcJVxyvNEEN9SMpQrjckwDLBOtwB0eHkoYR2wJfH9hd8brd7ZpVKUNw/TOuhepa5Qy5efEOqGMc+czHXrL3S1yAeYg05/iQg694s/rBTrAvpgM5Gclj4X3OLvYIzBmFbDmdmchkWohuioeDs9s1DYpvf4C5sgsUDzGPGzlH607BBYUYUtdrdCwXZhTo5kIAwSWcnR2ubStDBmTDg2wPKWU2MArJixtX05McoKnWv45i5eHdy2VY3ceTIMjZ1nOavjcHuq9n//AINzPxnwKkbXJ+IhL6ELYGt51Ft8zMh8DudC81Y20aOGDHe5t75Ce5KrSMipcLjL4HnDDGLwTzJg==
    REACT_APP_AUTH0_DOMAIN: AgAVgbpoc8Ep6XBBZV4E0aWpubIvBsuZr93SzdOwg3DFxG6Y8VoiCQhmgwC2ApEexILFuEDhjd18yetoNNJZDu3NXwVApagMYcWjPqsFRPqyFIr36zQdeWV8egf3u7fI5098Ko6Ya9ZiU7d63srfGQwKG0G8gInWvFzC9RAd0EVKfyCZHdcaaLVpxeVr+Dr92iO39pdsUFLYGMbIGwqInuYAfSz6Kn9HDC13Opg2wbamBqXl4WzMfCoG4h6mQSOElZM1x2n597HHjuboI7SZrChNcakSaUmq06u/ohVaClYPnT6SkOzpaWaH8gqWqpJvJjABQBwGqy44SQDpVfKFulThNxz7yil7iEhf5ruYtJ0LZtE2Q1ooOM6psCHWTEANkrNGaAfD5IzwPxHNGi5Q/nD6zBBsz2q+ztGj8svK3E7TPdpEZxOVGElfNXZpp5cyDBLhlfWoyO/vkEOozU1B5qdjVZk3m+5c5A2ymYrsT4PcfHwvZHA8optxeZ1lSV7/AUWCJav9TMtdsyEqld/OyMuXCxaJYdsMfUk7ymAJKDuZ6nvnQIeq92gnA5kUfvqGlOf3AWu0G6+Ms1RL4y7Db2CM19mCzKu/2aEOAhQqu/nAi8noGHMFt15SDLkxHQqNnJxIbkoTJPsau/7cE3roGY1Dx8DRRfR9aE2R+uECwTaFFmAJY3wqSyxa3DNeRzXGojNekitJWM8cj0GgBwQs5/A96za25v7Ild14FQ==
  template:
    metadata:
      creationTimestamp: null
      name: provider
      namespace: default
    type: Opaque

