apiVersion: v1
kind: Service
metadata:
  namespace: saas-provider-frontend
  name: saas-provider-frontend-service
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-type: nlb
   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:427398298435:certificate/d549015f-a332-4644-99c7-642c1a244491
   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
   service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: saas-provider-frontend