name: Deploy

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-2
  EKS_CLUSTER_NAME: saas-eks

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: cancue/eks-action@v0.0.2
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: $AWS_REGION
          cluster_name: $EKS_CLUSTER_NAME
        with:
          args: |
            kubectl apply -f kubernetes/namespace.yaml
            kubectl apply -f kubernetes/provider-sealed-secrets.yaml
            kubectl apply -f kubernetes/deployment.yaml
            kubectl apply -f kubernetes/service.yaml

